### ISSUE TITLE
Version 0.2.0

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif#89] opened 2020-08-27 14:30 UTC
Will have the changes in MMIF as discussed the last few weeks.

- Using text documents in views
- Using alignments for relating text documents to images or speech segments
- Getting rid of the contexts
- More example files

I am not sure what major changes in there are in the SDK, but it would be nice to have a checklist here.

- Updated to work with new specifications
- Added ability to freeze read-only parts of the MMIF file

We decided to use versions like `spec-0.2.0` and `py-0.2.0`, but we never added any tags to the repository for the previous version.

I started a branch `spec-0.2.0` for the changes on the specifications end, this will include changes to the publish script.

**Comment by keighrim** [comment] 2020-08-27 17:31
We have `py-0.1.0` and `spec-0.1.0` [tags](https://github.com/clamsproject/mmif/tags).

**Comment by marcverhagen** [comment] 2020-08-27 18:25
I cannot believe I did not see those. I updated the tag names in the first comment.

**Comment by marcverhagen** [comment] 2020-08-28 20:43
Checklist of things to do for `spec-0.2.0`:

- [ ]  Finish specification document.
- [ ]  Move and update examples used for the redesign discussion.
- [ ]  Change the schema.
- [ ]  Remove the contexts (if needed, we could just keep them, but not publish them.
- [ ]  Update the vocabulary (add document types, add document properties).
- [ ]  Update the publish script.
- [ ]  Add published specifications to the repository.
- [ ]  Update the `VERSION` file or delete it if we do not use it.
- [ ]  Test `mmif-python/Makefile`. 
- [ ]  Update `README.md` with notes on how to update the specifications.

**Comment by marcverhagen** [comment] 2020-08-28 21:08
See https://github.com/clamsproject/mmif/blob/86-vocabulary-redesign/specifications/index.md for updated specifications document. Note that not all links work.

**Comment by marcverhagen** [comment] 2020-09-03 19:44
On the http://mmif.clams.ai page the footer has a link with the text `clams.ai` but its target is `mmif.clams.ai` so I think it goes to the wrong place, but I am not sure how to change this because it requires me to understand the `_includes` and configuration magic.

**Comment by marcverhagen** [comment] 2020-09-03 19:56
There is a file `docs/_data/versions.yml` which has hard-wired version numbers and it used in `docs/index.md`. I updated it, but I am not sure what else it may do and for all I know it might be updated automatically. Also, is this for the spec or sdk version numbers?

**Comment by marcverhagen** [comment] 2020-09-03 20:36
I get an error when I run the make file in `mmif/vocabulary/rdf`.

```
[16:33:43] .../vocabulary/rdf (spec-0.2.0)> make all
rm -rf target
./bin/vocab -V 0.2.0 --output target --rdf rdf clams.vocabulary 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Compiled vocabulary version 0.2.0
Processing Thing
.
.
Processing Alignment
Exception in thread "main" org.apache.jena.shared.BadURIException: Only well-formed absolute URIrefs can be included in RDF/XML output: <Object> Code: 57/REQUIRED_COMPONENT_MISSING in SCHEME: A component that is required by the scheme is missing.
	at org.apache.jena.rdfxml.xmloutput.impl.BaseXMLWriter.checkURI(BaseXMLWriter.java:838)
        .
        .
        at ai.clams.mmif.formats.Formats.main(Formats.groovy:810)
make: *** [rdf] Error 1
```

An RDF file is created in the target directory, but nothing else. As far as I can tell all URIs in `clams.vocabulary` look good.

**Comment by angus-lherrou** [comment] 2020-09-03 20:46
Lovely.

**Comment by angus-lherrou** [comment] 2020-09-03 20:47
I'll dig into that tonight

**Comment by marcverhagen** [comment] 2020-09-03 21:07
I was running that on the `spec-0.2.0` branch.

**Comment by marcverhagen** [comment] 2020-09-03 21:10
Need to decide on what to put in the `CHANGELOG.md` file. Probably need to add both spec and sdk versions to the file.

**Comment by angus-lherrou** [comment] 2020-09-04 02:36
Okay, here's the thing that is causing that RDF issue.

```yaml
name: TextDocument
parent: Document

description: >-
  A text document.

properties:
  text:
    type: Object
    description: >-
      A JSON-LD value object which has a *@value* and a *@language* property.
```

We don't currently have `Object` in the type map:

```groovy
TYPE_MAP = [
    ID: XSD.ID,
    "URI": XSD.anyURI,
    "Integer": XSD.xlong,
    "List of IDs": IDREFS,
    "List of URI": ResourceFactory.createResource("$DATATYPE#list_uri"),
    "List of Strings": ResourceFactory.createResource("$DATATYPE#string_list"),
    "List of pairs": ResourceFactory.createResource("$DATATYPE#pair_list"),
    "Set of IDs": IDREFS,
    "String": XSD.xstring,
    "String or URI": XSD.xstring
]
```

Do either of you know the appropriate XSD data type equivalent to a JSON Object?

**Comment by angus-lherrou** [comment] 2020-09-04 02:41
(Confirmed that that was the problem: adding
```groovy
"Object": ResourceFactory.createResource('https://json-schema.org/understanding-json-schema/reference/object.html')
```
to the type map allows it to run without issues.

**Comment by keighrim** [comment] 2020-09-04 11:32
As MMIF is no longer a linked data format, I don't think we should convert and publish rdf and/or other linked data formats.

**Comment by marcverhagen** [comment] 2020-09-04 13:50
> Okay, here's the thing that is causing that RDF issue.

I see, I cannot just make up a type, no matter how general, good to know there is a restricted list.

> Do either of you know the appropriate XSD data type equivalent to a JSON Object?

The list of built-in data types at https://www.w3.org/TR/xmlschema-2/#built-in-datatypes only has simple types. I wonder whether we have to define a complex type. What are the types defined on XSD?

> As MMIF is no longer a linked data format, I don't think we should convert and publish rdf and/or other linked data formats.

It actually still is LSOND-LD, we are just using a small part of it and chucked out the contexts. We could give up all pretense and go full JSON.

**Comment by marcverhagen** [comment] 2020-09-04 19:51
@keighrim @angus-lherrou 

I have merged `spec-0.2.0` into `develop`. I do not want to tag this yet because many of the links in the website are broken and I have a hard time figuring out how to deal with all the github pages and jekyll magic. As far as I am concerned it is weird that `schema/mmif.json` in an href expands to `/0.2.0/schema/mmif` but `vocabulary` expands to `vocabulary`.

So while I do not want to tag that crap, all the stuff you need for py-0.2.0 is in `develop` now so you can just branch from there for your stuff. I will not change anything in the vocabulary or the schema.

On the side, and just to vent my irritation, I tried to install a new Ruby and Jekyll, which took more than an hour. The first succeeded and the second failed. But with `brew install ruby` I got all kinds of other crap reinstalled and installed under different names including a Python 3.8 which took over my python3 command. Sigh. Also, isn't it funny that the instructions to install Ruby say that you first need to install homebrew with a ruby command and then install ruby with brew. I can see how it works, but weird it is.

**Comment by keighrim** [comment] 2020-09-04 20:24
Yeah, all brew magic is only possible because there is a default ruby installed from the beginning. However, Apple is dropping many default script interpreters starting from osxi (bigsur), including ruby, python, bash, perl, and many. So probably in very near future, you'll be relying `pkg` installer for installing system applications anyway. Wait, where was I doing that? Ah, yeah, on Windows, I needed to run `exe` installers all the time. (even Windows now has a package manager `apt` via WSL)

**Comment by angus-lherrou** [comment] 2020-09-04 20:33
I think that's for the best, honestly. For developers it's a couple extra steps to install those things, no big deal, and then you're back up and running, plus you know where everything is and you don't have weird Apple-fied versions of things.

**Comment by keighrim** [comment] 2020-09-07 03:30
Back to the topic, for `mmif-python` 0.2.0 release we need, 
* (optional) publish 0.1.0 documentation (built by sphinx) as a part of `mmif.clams.ai` website
* update code
* update documentation 
* publish 0.2.0 documentation as a part of `mmif.clams.ai` website
* build and publish python dist to pypi.org 

Of course, updating code itself will be the largest task that comes with many small subtasks.

**Comment by keighrim** [comment] 2020-09-19 22:01
cabec75eb8b141ec7a408d19a4ab25b63fbb999f updates `serialize` code, reflecting changes in `spec-0.2.0`. Test code is not updated, so most of old tests are failing.

**Comment by keighrim** [comment] 2020-10-07 10:20
Although sphinx documentation wasn't release as part of it, `py-0.2.0` is release via #114 and uploaded to pypi. Closing this issue.

**Closed by keighrim** 2020-10-07 10:20 UTC
